
server:
  # 应用服务 WEB 访问端口
  port: 8080
  servlet:
    context-path: /boke

spring:

  application:
    # 应用名称
    name: boke

  thymeleaf:
    prefix:
      # 访问template下的html文件需要配置模板
      classpath: classpath:/templates/
    # 是否启用缓存
    cache: false
    # 模板文件后缀
    suffix: .html
    # 模板文件编码
    encoding: utf-8
    servlet:
      content-type: text/html

  redis:
    host: localhost
    port: 6379
    database: 6
    password:

  datasource:
    name: myBlog
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: Mysql123$
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxOpenPreparedStatements: 20
      #开启StatFilter
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        #开启Slf4jFilter
        slf4j:
          enabled: true
          data-source-log-enabled: false
          connection-log-enabled: false
          statement-log-enabled: false
          result-set-log-enabled: false
        #开启WallFilter
        wall:
          enabled: true
          log-violation: true
          throw-exception: false
          config:
            delete-where-none-check: true
      #开启Web监控
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
      #开启监控页面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: z1320291471

mybatis-plus:
  type-aliases-package: com.wwh.boke.entity
  mapper-locations: classpath*:mapper/*.xml


logging:
  level.com.site.blog: debug

upload:
  uploadAuthorImg: "D:/tmp/myblog/authorImg/"
  fileUploadDic: "D:/tmp/myblog/upload/"
  sqlAuthorImg: "/authorImg/"
  fileSqlDic: "/upload/"

